# This file was generated by GoReleaser. DO NOT EDIT.
cask "meibel" do
  version "2.0.12"

  on_macos do
    on_intel do
      sha256 "c688aab8cb44c431b322c345a97866cfe93cb5c63ebf8efcaa7ecf874f59ea38"
      url "https://github.com/meibel-ai/meibel-cli/releases/download/v#{version}/meibel_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "be2cb54286289ee2850c14f21f7c383be5e61f522d33f7ed10c92d853d6e3d67"
      url "https://github.com/meibel-ai/meibel-cli/releases/download/v#{version}/meibel_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "abcd22699fd9d9fef3336f14c08db5235efc8e16f20a5c3cc13bc9bc64742359"
      url "https://github.com/meibel-ai/meibel-cli/releases/download/v#{version}/meibel_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "105f7d7022972e9ca0d9af0a76713b21bab2fa4b83f0a8c5b0ce33e601cb45ce"
      url "https://github.com/meibel-ai/meibel-cli/releases/download/v#{version}/meibel_linux_arm64.tar.gz"
    end
  end

  name "meibel"
  desc "CLI for the meibel-ai-api API"
  homepage "https://github.com/meibel-ai/meibel-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "meibel"

  preflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/meibel"]
  end

  generate_completions_from_executable "meibel", "completion",
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
