# This file was generated by GoReleaser. DO NOT EDIT.
cask "meibel" do
  version "2.0.10"

  on_macos do
    on_intel do
      sha256 "9aacc9eacfe94bab49d230398cb22377de0451f803929b926682ba86579838f0"
      url "https://github.com/meibel-ai/meibel-cli/releases/download/v#{version}/meibel_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "736cd694c3683200c52f909052c34415ada9a31e2bb00f9db9dc32fb8173c1d8"
      url "https://github.com/meibel-ai/meibel-cli/releases/download/v#{version}/meibel_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bf583344ebc89a11024fcc09cce9158ec1cf107b674d3bc3b42e116fee3ba69f"
      url "https://github.com/meibel-ai/meibel-cli/releases/download/v#{version}/meibel_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e3eabae8f328d08baf7d1321f00720ae79899303b03af86e0f0b0bb921628a42"
      url "https://github.com/meibel-ai/meibel-cli/releases/download/v#{version}/meibel_linux_arm64.tar.gz"
    end
  end

  name "meibel"
  desc "CLI for the meibel-ai-api API"
  homepage "https://github.com/meibel-ai/meibel-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "meibel"

  preflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/meibel"]
  end

  generate_completions_from_executable "meibel", "completion",
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
