# This file was generated by GoReleaser. DO NOT EDIT.
cask "meibel" do
  version "2.0.8"

  on_macos do
    on_intel do
      sha256 "e8ef4d88710c6c97260cffcef75f97a80ecb51cd4b4b16a3653db2941bbc5792"
      url "https://github.com/meibel-ai/meibel-cli/releases/download/v#{version}/meibel_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d1663b109b2d48e55b005c6ee390649bc8df11fc6cbce5f1b588ab042a59e958"
      url "https://github.com/meibel-ai/meibel-cli/releases/download/v#{version}/meibel_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f295a7d6f2ba109db48418aaa7f1a7611247dc231f209d3e8680f43b8074bcb2"
      url "https://github.com/meibel-ai/meibel-cli/releases/download/v#{version}/meibel_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "926806fcd4ae7c0680d960b2c48da4b6203a1c68990debc177969fd184acbac4"
      url "https://github.com/meibel-ai/meibel-cli/releases/download/v#{version}/meibel_linux_arm64.tar.gz"
    end
  end

  name "meibel"
  desc "CLI for the meibel-ai-api API"
  homepage "https://github.com/meibel-ai/meibel-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "meibel"

  generate_completions_from_executable "meibel", "completion",
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
