# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Meibel < Formula
  desc "CLI for interacting with Meibel AI API"
  homepage "https://github.com/meibel-ai/meibel-cli"
  version "0.1.0-beta.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/meibel-ai/meibelai-cli/releases/download/v0.1.0-beta.6/meibel_Darwin_x86_64.tar.gz"
      sha256 "394ac837fb9e3cac58a1d1ed3849c5e1daa2b3302925495fe3673cc45f08aa37"

      define_method(:install) do
        bin.install "meibel"
        bash_completion.install "completions/meibel.bash" => "meibel"
        zsh_completion.install "completions/meibel.zsh" => "_meibel"
        fish_completion.install "completions/meibel.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/meibel-ai/meibelai-cli/releases/download/v0.1.0-beta.6/meibel_Darwin_arm64.tar.gz"
      sha256 "68d2dca7b049be0e2e0d38250d730c76feaff26b0e052966b4d4758211257ad8"

      define_method(:install) do
        bin.install "meibel"
        bash_completion.install "completions/meibel.bash" => "meibel"
        zsh_completion.install "completions/meibel.zsh" => "_meibel"
        fish_completion.install "completions/meibel.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/meibel-ai/meibelai-cli/releases/download/v0.1.0-beta.6/meibel_Linux_x86_64.tar.gz"
      sha256 "20de332ccc112189e7d040b3ad60491d8585ad276e7f441e107d71441e003e87"
      define_method(:install) do
        bin.install "meibel"
        bash_completion.install "completions/meibel.bash" => "meibel"
        zsh_completion.install "completions/meibel.zsh" => "_meibel"
        fish_completion.install "completions/meibel.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/meibel-ai/meibelai-cli/releases/download/v0.1.0-beta.6/meibel_Linux_arm64.tar.gz"
      sha256 "e34c874e0483da8ad163e26663074392bda83edade35ee5c3ad642a4aa6e77e8"
      define_method(:install) do
        bin.install "meibel"
        bash_completion.install "completions/meibel.bash" => "meibel"
        zsh_completion.install "completions/meibel.zsh" => "_meibel"
        fish_completion.install "completions/meibel.fish"
      end
    end
  end

  def caveats
    <<~EOS
      To configure authentication, run:
        meibel auth login

      For more information, visit:
        https://github.com/meibel-ai/meibel-cli
    EOS
  end

  test do
    system "#{bin}/meibel version"
  end
end
