# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Meibel < Formula
  desc "CLI for interacting with Meibel AI API"
  homepage "https://github.com/meibel-ai/meibel-cli"
  version "0.1.0-beta.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/meibel-ai/meibelai-cli/releases/download/v0.1.0-beta.5/meibel_Darwin_x86_64.tar.gz"
      sha256 "72abfae3a5379da7fb228c7314cd0ab93dad1ce65f0159eac45ecc6603115a9e"

      define_method(:install) do
        bin.install "meibel"
        bash_completion.install "completions/meibel.bash" => "meibel"
        zsh_completion.install "completions/meibel.zsh" => "_meibel"
        fish_completion.install "completions/meibel.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/meibel-ai/meibelai-cli/releases/download/v0.1.0-beta.5/meibel_Darwin_arm64.tar.gz"
      sha256 "d80955a103522abda39dd6e7d789e56576993e0a2f8529649be9cc131bbe9d8a"

      define_method(:install) do
        bin.install "meibel"
        bash_completion.install "completions/meibel.bash" => "meibel"
        zsh_completion.install "completions/meibel.zsh" => "_meibel"
        fish_completion.install "completions/meibel.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/meibel-ai/meibelai-cli/releases/download/v0.1.0-beta.5/meibel_Linux_x86_64.tar.gz"
      sha256 "33fce9b194a0b4ceddf596526f28dd9a0ddd63dc902f7c79cfcdd907fa85bc15"
      define_method(:install) do
        bin.install "meibel"
        bash_completion.install "completions/meibel.bash" => "meibel"
        zsh_completion.install "completions/meibel.zsh" => "_meibel"
        fish_completion.install "completions/meibel.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/meibel-ai/meibelai-cli/releases/download/v0.1.0-beta.5/meibel_Linux_arm64.tar.gz"
      sha256 "a26748c9be98c0b1325636ff5112ae96256c6aff401878f7a410cabf1de910fe"
      define_method(:install) do
        bin.install "meibel"
        bash_completion.install "completions/meibel.bash" => "meibel"
        zsh_completion.install "completions/meibel.zsh" => "_meibel"
        fish_completion.install "completions/meibel.fish"
      end
    end
  end

  def caveats
    <<~EOS
      To configure authentication, run:
        meibel auth login

      For more information, visit:
        https://github.com/meibel-ai/meibel-cli
    EOS
  end

  test do
    system "#{bin}/meibel version"
  end
end
