# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Meibel < Formula
  desc "CLI for interacting with Meibel AI API"
  homepage "https://github.com/meibel-ai/meibel-cli"
  version "0.1.0-beta.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/meibel-ai/meibelai-cli/releases/download/v0.1.0-beta.7/meibel_Darwin_x86_64.tar.gz"
      sha256 "39db8587d5e527d80928afff009e7de344e46ed2f393016439bfb45e225245f8"

      define_method(:install) do
        bin.install "meibel"
        bash_completion.install "completions/meibel.bash" => "meibel"
        zsh_completion.install "completions/meibel.zsh" => "_meibel"
        fish_completion.install "completions/meibel.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/meibel-ai/meibelai-cli/releases/download/v0.1.0-beta.7/meibel_Darwin_arm64.tar.gz"
      sha256 "187cf63764a6e0af32bf6aa26649c5fe250ebf44cad4633e0a7233c2cc02b4e6"

      define_method(:install) do
        bin.install "meibel"
        bash_completion.install "completions/meibel.bash" => "meibel"
        zsh_completion.install "completions/meibel.zsh" => "_meibel"
        fish_completion.install "completions/meibel.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/meibel-ai/meibelai-cli/releases/download/v0.1.0-beta.7/meibel_Linux_x86_64.tar.gz"
      sha256 "53fb58bd2a4c9fd520e0e51280c9b30345f8c419e8842b46401d6ab41c0157e7"
      define_method(:install) do
        bin.install "meibel"
        bash_completion.install "completions/meibel.bash" => "meibel"
        zsh_completion.install "completions/meibel.zsh" => "_meibel"
        fish_completion.install "completions/meibel.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/meibel-ai/meibelai-cli/releases/download/v0.1.0-beta.7/meibel_Linux_arm64.tar.gz"
      sha256 "7cd9c2dff57f28d14f976de87dd0860486aff27cb2d670d3a3bf8f350d52ff0e"
      define_method(:install) do
        bin.install "meibel"
        bash_completion.install "completions/meibel.bash" => "meibel"
        zsh_completion.install "completions/meibel.zsh" => "_meibel"
        fish_completion.install "completions/meibel.fish"
      end
    end
  end

  def caveats
    <<~EOS
      To configure authentication, run:
        meibel auth login

      For more information, visit:
        https://github.com/meibel-ai/meibel-cli
    EOS
  end

  test do
    system "#{bin}/meibel version"
  end
end
